#spring:
#  application:
#    name: activity-service
#  config:
#    import: optional:configserver:http://localhost:8888
#
#
#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#


spring:
  application:
    name: activity-service
  cloud:
    config:
      overrideSystemProperties: true
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: localhost:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

