#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: aiactivityfitness
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#kafka:
#  topic:
#    name: activity-events
#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#server:
#  port: 8082
#
spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@cluster0.ep1hkvd.mongodb.net/
      database: AI-Fitness

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: |
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="${KAFKA_USERNAME}"
        password="${KAFKA_PASSWORD}";
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


kafka:
  topic:
    name: activity-events

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: localhost:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/