#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/fitness-micro-user
#    username: postgres
#    password: admin@123
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#server:
#  port: 8081



spring:
  datasource:
    url: jdbc:postgresql://ep-lucky-credit-a4zcn6ta-pooler.us-east-1.aws.neon.tech:5432/AI-Fitness?sslmode=require
    username: ${NEON_USERNAME}
    password: ${NEON_PASSWORD}
#    url: jdbc:postgresql://localhost:5432/fitness-micro-user
#    username: postgres
#    password: admin@123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: localhost:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: https://eureka-server-6mb3.onrender.com/eureka/
